### ISSUE TITLE
能直接部署到服务器吗？

### ISSUE THREAD

**Issue by beilo** [AowerDmax/Simple-Interview-Audio-Processing#1]
我买了个华为云的 2g2m的小鸡，不知道这个项目支持直接部署到服务器嘛？

现在看只支持终端？不知道后续考虑开放网页或者api？

谢谢佬~

**Comment by AowerDmax** [comment]
支持的,我的电脑是一个小内存MAC,我在开发的时候,funsar语音识别和redis都是放在服务器上面开发的,本地测试了一下.更改.env里面的对应的HOST值就可以.
后面的开发计划应该会包含如下内容:
1. 使用websocket将对话记录(`interview`, `Rookie`, `Chatgpt`)推送到网页端, 这样你可以在电脑运行这个程序,然后在手机或者其他终端设备通过打开网页查看对话记录
2. 外接知识库,采用类似elasticsearch的进行知识库的搜索索引.(不用embedding的原因是需要额外付费)
3. 增加快捷键截屏发送给GPT进行屏幕内容识别和问题回答

最近有些其他的事情, 开发计划可能不会这么快上新.有哪些比较重要的Feature我可以赶一赶做出来

**Comment by beilo** [comment]
@AowerDmax 谢谢大佬～
