### ISSUE TITLE
报错出现两个REDIS_HOST

### ISSUE THREAD

**Issue by antsyan** [AowerDmax/Simple-Interview-Audio-Processing#3]
这里报错出现两个REDIS_HOST， line 20: mapping key "REDIS_HOST" already defined at line 19

**Comment by AowerDmax** [comment]
docker-compose.yml写的时候出了点问题,感谢指正,REDIS_HOST,REDIS_PORT,已经修改了,其实你也可以把
```bash
    environment:
      MEILISEARCH_HOST: "meilisearch"
      MEILISEARCH_PORT: 7700
      REDIS_HOST: "redis"
      REDIS_PORT: 6379
```
这些部分都删掉,然后这样就会使用.env里面设置的内容.
不删掉就是使用docker内部的通信机制
