### ISSUE TITLE
您好，启动docker的时候缺失docker file这个可以帮忙解决一下吗？始皇的群友哈哈

### ISSUE THREAD

**Issue by night-ssk** [AowerDmax/Simple-Interview-Audio-Processing#5]
failed to solve: failed to read dockerfile: open /var/snap/docker/common/var-lib-docker/tmp/buildkit-mount574725884/Dockerfile: no such file or directory

**Comment by AowerDmax** [comment]
那个是服务端,也就是负责 `多端 web` 展示的. 

项目地址在 [websocket-redis](https://github.com/AowerDmax/websocket-redis),这个里面有具体的`dockerfile`.

我使用`github actions`已经构建容器了,我修复了`docker compose` 文件.将构建好的容器地址填写进去了
